export const SET_PORTFOLIO_DATA = 'SET_PORTFOLIO_DATA';
export const SET_PORTFOLIO_DATA_FAILED = 'SET_PORTFOLIO_DATA_FAILED';

export const SET_PROJECTS_PROFESSIONAL = 'SET_PROJECTS_PROFESSIONAL';
export const SET_PROJECTS_PROFESSIONAL_FAILED = 'SET_PROJECTS_PROFESSIONAL_FAILED';
export const SET_PROJECTS_INDIVIDUAL = 'SET_PROJECTS_INDIVIDUAL';
export const SET_PROJECTS_INDIVIDUAL_FAILED = 'SET_PROJECTS_INDIVIDUAL_FAILED';

export const SET_PROJECT_IMAGES_LOADED = 'SET_PROJECT_IMAGES_LOADED';
export const SET_PROJECT_IMAGES_LOAD_FAILED = 'SET_PROJECT_IMAGES_LOAD_FAILED';

export const SET_OPEN_PROJECT = 'SET_OPEN_PROJECT';
export const SET_CLOSE_PROJECT = 'SET_CLOSE_PROJECT';

export const SET_ACHIEVEMENTS = 'SET_ACHIEVEMENTS';
export const SET_ACHIEVEMENTS_FAILED = 'SET_ACHIEVEMENTS_FAILED';

export const SET_SKILLS = 'SET_SKILLS';
export const SET_SKILLS_FAILED = 'SET_SKILLS_FAILED';

export const SET_CONTACT = 'SET_CONTACT';
export const SET_CONTACT_FAILED = 'SET_CONTACT_FAILED';

export const SET_OPEN_PREVIEW = 'SET_OPEN_PREVIEW';
export const SET_CLOSE_PREVIEW = 'SET_CLOSE_PREVIEW';